### ISSUE TITLE
使用View Table Data功能报错

### ISSUE THREAD

**Issue by cfm1120** [wangjiegulu/wangjiegulu.github.com#1]
替换你编译的jar包，是不提示License了，但是View Table Data功能报错，2.0.4和2.0.6都不行
官方的话是2.0.4不行，2.0.6可以。

Android Studio2.2

**Comment by wangjiegulu** [comment]
Android Studio版本是2.2.1吗？是的话替换2.0.6版本的SQLScout.jar

**Comment by cfm1120** [comment]
噢噢，可以了哈。可能前面我搞错了，安装了官方的2.0.6，但是替换的是2.0.4的jar包所以报错了。
安装2.0.6替换2.0.6的jar可以了，谢谢啊。Android Studio是2.2.1。 @wangjiegulu

**Comment by wangjiegulu** [comment]
OK

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by mugabutie** [comment]
e....报错了。。。NoClassDefFoundError: com/idescout/sqlite/console/D

**Comment by wangjiegulu** [comment]
@mugabutie 先确认`Android Studio版本、SQLScout插件版本、破解的SQLScout.jar版本`是否全都匹配一致（重要），如果都是匹配的，请把报错重现步骤描述下。

另外，连续疯狂刷屏是几个意思？？
