### ISSUE TITLE
你好，能请帮忙破解下2.0.8么？

### ISSUE THREAD

**Issue by a483210** [wangjiegulu/wangjiegulu.github.com#10]
你好，能请帮忙破解下2.0.8么？非常感谢

**Comment by mcxinyu** [comment]
我直接复制你破解文件里面的License.class到2.0.8，但是AndroidStudio好像不识别。

**Comment by wangjiegulu** [comment]
可以先使用2.0.7版本，2.0.8抽空会破解下

**Comment by a483210** [comment]
额，我的studio是2.3的，然后2.0.7使用好像会报错

**Comment by lyz12600** [comment]
麻烦帮忙破解下，前天刚装好，今天不能用了，提示
android sqlite data source(live connection).
connection failed.
试了好几次，都不能用了，急急急，大神帮忙破解下。

**Comment by wangjiegulu** [comment]
已破解，https://github.com/wangjiegulu/wangjiegulu.github.com/tree/master/file/SQLScout/2.0.8

**Comment by a483210** [comment]
谢谢

**Comment by jiangecho** [comment]
你好，请问SQLScout_console_part.jar这个文件是怎么生成的？
或者，请问可以写一个比较详细的破解教程吗？想学习下。

http://www.cnblogs.com/tiantianbyconan/p/5972138.html
上面只说到生成class，并重新打包成SQLScout.jar，但没有提到SQLScout_console_part.jar

谢谢
