### ISSUE TITLE
Could I only use the provided jar files

### ISSUE THREAD

**Issue by humazed** [wangjiegulu/wangjiegulu.github.com#12]
I read the tutorial throw google translation and couldn't understand if it is sufficient to only use the provided jars or I must use  javassist.

as I have tried to just replace the jar files but it doesn't work and keep asking me for licence.

**Comment by wangjiegulu** [comment]
You need not use `javassist`. 

- Shutdown your Android Studio.

- Make sure your SQLScout version is **2.0.8** first, and delete `SQLScout.jar` file in `~/Library/Application Support/AndroidStudio2.3/SQLScout/lib/`

- Copy [SQLScout.jar](https://github.com/wangjiegulu/wangjiegulu.github.com/blob/master/file/SQLScout/2.0.8/SQLScout.jar) and [SQLScout\_console\_part.jar](https://github.com/wangjiegulu/wangjiegulu.github.com/blob/master/file/SQLScout/2.0.8/SQLScout_console_part.jar) to `~/Library/Application Support/AndroidStudio2.3/SQLScout/lib/`

- Restart Android Studio.

**Comment by humazed** [comment]
Ok thank youl
