### ISSUE TITLE
NoClassDefFoundError: com/idescout/sqlite/console/D

### ISSUE THREAD

**Issue by mugabutie** [wangjiegulu/wangjiegulu.github.com#2]
e....报错了。。。

**Comment by wangjiegulu** [comment]
@mugabutie 先确认Android Studio版本、SQLScout插件版本、破解的SQLScout.jar版本是否全都匹配一致（重要），如果都是匹配的，请把报错重现步骤描述下。

另外，连续疯狂刷屏是几个意思？？
