### ISSUE TITLE
真机上不能使用,三星和小米

### ISSUE THREAD

**Issue by onebee** [wangjiegulu/wangjiegulu.github.com#9]
模拟器上可以使用,真机上面显示不出来应用程序的包名
![159b2d59-657f-4343-8cc4-e938ce18cafd](https://cloud.githubusercontent.com/assets/8468626/23246491/085b3cae-f9cf-11e6-867b-d6c21fc3cdc4.png)

**Comment by wangjiegulu** [comment]
确定应用程序debugable？

**Comment by mcxinyu** [comment]
手机应该要 root 才能使用，因为涉及到data目录下的权限问题。

**Comment by onebee** [comment]
真机上可以用了  上次不知道什么原因
